Modification on My Api Page side bar
Zummit-Africa-Inc/zapi-dummy-fe pull request #82
Opened 2022-07-22 16:28 UTC by Yagazie-davidson

## Contributions
- Implementation of the drop downs and the tabs.
- Fixed a bug on the Organization page (I just noticed it)
## TODO

- Analytics page

2022-07-22 17:45 UTC, taiwoAkindele approved these changes

2022-07-24 15:13 UTC, PhilemonBrain requested changes

2022-07-24 15:13 UTC, PhilemonBrain commented on src/App.js
> +			navigate(`/user/${profileId}`);
why are u navigating??? @Yagazie-davidson

2022-07-24 15:13 UTC, PhilemonBrain commented on src/components/OrgTeammates.jsx
> +	console.log(orgTeam);
remove these logs when you're pushing

2022-07-24 20:59 UTC, taiwoAkindele approved these changes

2022-07-24 20:59 UTC, taiwoAkindele commented on src/App.js
> +			navigate(`/user/${profileId}`);
The useNavigate hook is not imported, perhaps it was deleted by mistake.

2022-07-24 22:53 UTC, Yagazie-davidson commented on src/App.js
> +			navigate(`/user/${profileId}`);
This isn't my code

2022-07-25 06:30 UTC, PhilemonBrain requested changes

2022-07-25 06:30 UTC, PhilemonBrain commented on src/App.js
> +			navigate(`/user/${profileId}`);
then there is an issue. it means you're not updated on the main branch @Yagazie-davidson

2022-07-25 09:42 UTC, closed without merging