David bradford
Zummit-Africa-Inc/zapi-dummy-fe pull request #84
Opened 2022-07-24 14:23 UTC by deviator53

- created a change password page
- did a cleanup of password reset, email verified and route to match with backend url

2022-07-24 15:54 UTC, PhilemonBrain requested changes

2022-07-24 15:54 UTC, PhilemonBrain commented on src/pages/ForgotPassword.jsx
> +        setTimeout(() => {
why this setTimeout?

2022-07-24 15:54 UTC, PhilemonBrain commented on src/pages/PasswordReset.jsx
> +				const res = await axios.post(url, { password, passwordConfirm });
we have a fetch hook. try and use it

2022-07-24 15:54 UTC, PhilemonBrain commented on src/pages/PasswordReset.jsx
> +				setTimeout(()=> {
why setTimeout? what are u trying to achieve

2022-07-24 15:54 UTC, PhilemonBrain commented on src/App.js
> +          <Route path='/change-password' element={<ChangePassword />} />
where did u handle the password strength check?

2022-07-24 20:41 UTC, taiwoAkindele approved these changes

2022-07-24 20:41 UTC, taiwoAkindele commented on src/App.js
> +import ChangePassword from './pages/ChangePassword'
add the EmailVerify and other pages you worked on to the index.js in the pages folder and export them from there.

2022-07-24 20:41 UTC, taiwoAkindele commented on src/App.js
> +import ChangePassword from './pages/ChangePassword'
add the ChangePassword and other pages you worked on to the index.js in the pages folder and export them from there.

2022-07-24 20:41 UTC, taiwoAkindele commented on src/pages/ChangePassword.jsx
> +const ChangePassword = () => {
I don't think this is working yet or is it? @deviator53

2022-07-25 10:22 UTC, PhilemonBrain approved these changes

2022-07-25 10:25 UTC, merged